# Generated by Django 3.2.9 on 2022-05-09 09:04

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=250)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='NewsLetterRecipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('email', models.EmailField(max_length=256, null=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('flavour', models.CharField(choices=[('CHOCOLATE FUDGE', 'CHOCOLATE FUDGE'), ('CHOCOLATE MINT', 'CHOCOLATE MINT'), ('CHOCOLATE CHIP', 'CHOCOLATE CHIP'), ('RED VELVET', 'RED VELVET'), ('BLUE VELVET', 'BLUE VELVET'), ('GREEN VELVET', 'GREEN VELVET'), ('VANILLA', 'VANILLA'), ('COFFEE', 'COFFEE'), ('COCONUT', 'COCONUT'), ('GINGER', 'GINGER'), ('ZEBRA', 'ZEBRA'), ('CINNAMON', 'CINNAMON'), ('SPICE', 'SPICE'), ('MARBLE', 'MARBLE'), ('PINA COLADA', 'PINA COLADA'), ('LEMON', 'LEMON'), ('LIME', 'LIME'), ('BANANA', 'BANANA'), ('ORANGE', 'ORANGE'), ('PASSION JUICE', 'PASSION JUICE'), ('BUBBLEGUM', 'BUBBLEGUM'), ('CARROT', 'CARROT'), ('MINT', 'MINT'), ('OREO', 'OREO'), ('CARAMEL', 'CARAMEL'), ('BLUEBERRY', 'BLUEBERRY'), ('STRAWBERRY', 'STRAWBERRY'), ('BUTTER', 'BUTTER'), ('FRUIT', 'FRUIT'), ('BLACK FOREST', 'BLACK FOREST'), ('WHITE FOREST', 'WHITE FOREST'), ('BLUEBERRY FOREST', 'BLUEBERRY FOREST'), ('PASSION FRUIT FOREST', 'PASSION FRUIT FOREST')], default='VANILLA', max_length=60)),
                ('topping', models.CharField(choices=[('SKITTLES', 'SKITTLES'), ('GUMMIES', 'GUMMIES'), ('FRUITS', 'FRUITS'), ('NUTS', 'NUTS'), ('OREOS', 'OREOS'), ('CHERRIES', 'CHERRIES'), ('CAKE SAIL', 'CAKE SAIL'), ('CAKE TOPPERS', 'CAKE TOPPERS'), ('ASSORTED CHOCOLATES', 'ASSORTED CHOCOLATES')], default='GUMMIES', max_length=60)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=60)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
